#!/bin/bash
export NEBULAE_KEYCLOAK_IMAGE_NAMESPACE=nebulae
export NEBULAE_KEYCLOAK_IMAGE_NAME=keycloak
export NEBULAE_KEYCLOAK_IMAGE_TAG=3.4.3.11

docker build  -t $NEBULAE_KEYCLOAK_IMAGE_NAMESPACE/$NEBULAE_KEYCLOAK_IMAGE_NAME:$NEBULAE_KEYCLOAK_IMAGE_TAG -t $NEBULAE_KEYCLOAK_IMAGE_NAMESPACE/$NEBULAE_KEYCLOAK_IMAGE_NAME:latest mods/