FROM busybox
LABEL Author=sebastian.molano@nebulae.com.co
# default themes
COPY keycloak /mythemes
# trik theme
COPY themes/trikBase /mythemes/trikBase
COPY themes/trikKeycloak /mythemes/trikKeycloak
# txplus client theme
COPY themes/txPlusBase /mythemes/txPlusBase
COPY themes/txPlusKeycloak /mythemes/txPlusKeycloak
